name: Create Zip on Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Release Zip
    runs-on: windows-latest
    permissions: write-all
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Compile Sources
      run: make
    
    - name: Create Release Zip
      run: |
        copy amk_spc_dump.bat build
        copy readme.txt build
        cd build
        tar -czf amk_spc_dump-${{ github.event.release.tag_name }}.tar.gz *.exe *.bat *.txt
        ls
        copy amk_spc_dump-${{ github.event.release.tag_name }}.tar.gz ..
        cd ..
        rm -r build
        ls

    - name: Install GitHub CLI
      run: |
        choco install gh

    - name: Upload Release Zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} amk_spc_dump-${{ github.event.release.tag_name }}.tar.gz
        
